alias tmux="tmux2"
alias python="python3"
alias gentagpy="ctags -L <(find . -name '*.py' | cut -c3-) --fields=+iaS --python-kinds=-i --extra=+q -f .git/python.tags"
alias gco="git checkout"
alias gdc="git diff --cached"
alias gpom="git push origin master"
alias gmnf="git merge --no-ff"
alias gcm="git commit -m "
